install_mode: "full"
resource_package: "example/resources-ubuntu-amd64.tar.gz"
#resource_package: "xxx.tar.gz"

# 组件部署配置（默认不启用）
addons:
  kube_ovn:
    enabled: true
  multus_cni:
    enabled: true
  hami:
    enabled: true
  kube_prometheus_stack:
    enabled: true

# 仅执行预检查，不执行安装动作
dry_run: true

# 私有仓库配置
registry:
  endpoint: "ykl.io"
  port: 8080
  ip: 192.168.31.175
  username: "admin"
  password: "Harbor12345"

# 节点列表（按顺序进行安装）
nodes:
  - ip: "192.168.31.150"
    password: "root"
    ssh_port: 22
    is_master: true
  - ip: "192.168.31.92"
    password: "root"
    ssh_port: 22
  - ip: "192.168.31.169"
    password: "root"
    ssh_port: 22

# Worker 节点加入集群的命令 (在 is_master: false 的节点上执行)
join_command: ""
