install_mode: "addons-only"
resource_package: "example/resources-ubuntu-amd64.tar.gz"

# 组件部署配置（默认不启用）
addons:
  kube_ovn:
    enabled: true
  multus_cni:
    enabled: true
  hami:
    enabled: true
  kube_prometheus_stack:
    enabled: true

# 仅执行预检查，不执行安装动作
dry_run: false

# 私有仓库配置
registry:
  endpoint: "jusuan.io"
  port: 8080
  ip: 10.10.10.250
  username: "admin"
  password: "Harbor12345"

# 三 Master 高可用配置
ha:
  enabled: true
  virtual_ip: "10.10.10.150/24"

# 节点列表（按顺序进行安装）
nodes:
  - ip: "10.10.10.50"
    password: "root"
    ssh_port: 22
    is_master: true
    is_primary_master: true
    interface: "ens18"
  - ip: "10.10.10.51"
    password: "root"
    ssh_port: 22
    is_master: true
    interface: "ens18"
  - ip: "10.10.10.52"
    password: "root"
    ssh_port: 22
    is_master: true
    interface: "ens18"
  - ip: "10.10.10.60"
    password: "root"
    ssh_port: 22
  - ip: "10.10.10.61"
    password: "root"
    ssh_port: 22
  - ip: "10.10.10.70"
    password: "root"
    ssh_port: 22



