# 全量配置示例

# 全局 SSH 默认设置
ssh_port: 22
user: "root"
# 命令执行超时（秒）
command_timeout_seconds: 600

# 软件版本定义
versions:
  containerd: "2.2.1"
  runc: "1.3.4"
  nerdctl: "2.2.1"
  k8s: "1.35.0"

# 私有仓库配置
registry:
  endpoint: "ykl.io"
  port: 40443
  ip: 192.168.1.7

# 节点列表（按顺序进行安装）
nodes:
  - ip: "192.168.31.133"
    password: "root"
    ssh_port: 22
    is_master: true
    install_tools: true

# Worker 节点加入集群的命令 (在 is_master: false 的节点上执行)
join_command: "kubeadm join 192.168.1.10:6443 --token <token> --discovery-token-ca-cert-hash <hash>"
