images:
  - docker.io/busybox:latest
  - docker.io/rancher/kubectl:v1.35.0
  - ghcr.io/prometheus-community/windows-exporter:v0.31.3
  - quay.io/prometheus/alertmanager:v0.31.0
  - docker.io/grafana/grafana:12.3.2
  - docker.io/bats/bats:1.13.0
  - docker.io/curlimages/curl:8.18.0
  - docker.io/library/busybox:1.37.0
  - docker.io/grafana/grafana-image-renderer:latest
  - quay.io/kiwigrid/k8s-sidecar:2.5.0
  - registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.18.0
  - quay.io/brancz/kube-rbac-proxy:v0.20.2
  - quay.io/prometheus/node-exporter:v1.10.2
  - quay.io/brancz/kube-rbac-proxy:v0.20.2
  - quay.io/prometheus-operator/admission-webhook:v0.88.1
  - ghcr.io/jkroepke/kube-webhook-certgen:1.7.4
  - quay.io/prometheus-operator/prometheus-operator:v0.88.1
  - quay.io/prometheus-operator/prometheus-config-reloader:v0.88.1
  - quay.io/thanos/thanos:v0.40.1
  - quay.io/prometheus/prometheus:v3.9.1
  - quay.io/thanos/thanos:v0.40.1
